apiVersion: 1

datasources:
  - name: "fermilab-graphql-datasource"
    uid: "fermilab-graphql-datasource"
    type: 'datasource'
    access: 'direct'
    isDefault: true
    orgId: 1
    version: 1
    editable: true
    url: http://datasource:8888/api
